//! Runs `flowsentinel inspect --decode` against the application-protocol
//! fixtures (app-*.pcap) generated by scripts/generate_pcap_fixtures.py.

use std::path::PathBuf;
use std::process::{Command, Output};

use serde_json::{Value, json};

/// Every credential-like value in the fixtures contains this marker.
const SECRET_MARKER: &str = "FLOWSENTINEL-SECRET";
const PAYLOAD_MARKER: &str = "FLOWSENTINEL-SYNTHETIC-PAYLOAD-MARKER";

fn run(name: &str, extra: &[&str]) -> Output {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/pcap")
        .join(name);
    Command::new(env!("CARGO_BIN_EXE_flowsentinel"))
        .arg("inspect")
        .arg("--pcap")
        .arg(path)
        .args(extra)
        .output()
        .expect("failed to run flowsentinel binary")
}

fn packets(name: &str) -> Vec<Value> {
    let out = run(name, &["--decode", "--json"]);
    assert_eq!(out.status.code(), Some(0), "{name}");
    let report: Value = serde_json::from_slice(&out.stdout).expect("one JSON object");
    report["packets"].as_array().unwrap().clone()
}

/// The application layer of a packet, if any.
fn app(packet: &Value) -> Option<&Value> {
    packet["decoded"]["layers"]
        .as_array()
        .unwrap()
        .iter()
        .find(|l| matches!(l["layer"].as_str(), Some("dns" | "dhcp" | "http" | "tls")))
}

fn warning_codes(packet: &Value) -> Vec<String> {
    packet["decoded"]["warnings"]
        .as_array()
        .unwrap()
        .iter()
        .map(|w| w["code"].as_str().unwrap().to_owned())
        .collect()
}

#[test]
fn dns_fixture() {
    let p = packets("app-dns.pcap");
    assert_eq!(p.len(), 12);

    let query = app(&p[0]).unwrap();
    assert_eq!(query["is_response"], false);
    assert_eq!(query["transaction_id"], 0x1A2B);
    assert_eq!(query["recursion_desired"], true);
    assert_eq!(
        query["questions"][0],
        json!({"name": "www.example.com", "record_type": 1, "type_name": "A", "class": 1})
    );

    let response = app(&p[1]).unwrap();
    assert_eq!(response["response_code_name"], "NOERROR");
    assert_eq!(response["answers"][0]["type_name"], "CNAME");
    assert_eq!(response["answers"][0]["data"], "web.example.com");
    assert_eq!(response["answers"][1]["name"], "web.example.com");
    assert_eq!(response["answers"][1]["data"], "198.51.100.80");

    assert_eq!(app(&p[3]).unwrap()["answers"][0]["data"], "2001:db8::80");
    assert_eq!(app(&p[4]).unwrap()["response_code_name"], "NXDOMAIN");
    assert_eq!(
        app(&p[5]).unwrap()["answers"][0]["data"],
        "10 mail.example.com"
    );
    // TXT contents are never shown, only their length.
    let txt = &app(&p[6]).unwrap()["answers"][0];
    assert_eq!(txt["data"], Value::Null);
    assert_eq!(txt["data_length"], 24);
    // mDNS cache-flush bit is masked out of the class.
    assert_eq!(app(&p[7]).unwrap()["answers"][0]["class"], 1);
    // Compression loop: recognized, answer rejected.
    assert_eq!(p[8]["decoded"]["status"], "malformed");
    assert_eq!(warning_codes(&p[8]), ["malformed_application_data"]);
    // DNS over TCP.
    assert_eq!(app(&p[9]).unwrap()["transport"], "tcp");
    // Not DNS on port 53.
    assert!(app(&p[10]).is_none());
    assert_eq!(warning_codes(&p[10]), ["unrecognized_application_data"]);
    // Response cut by the snapshot length.
    assert_eq!(p[11]["decoded"]["status"], "truncated");
}

#[test]
fn dhcp_fixture() {
    let p = packets("app-dhcp.pcap");
    let types: Vec<Value> = p
        .iter()
        .map(|x| app(x).map_or(Value::Null, |a| a["message_type_name"].clone()))
        .collect();
    assert_eq!(
        types,
        [
            json!("DHCPDISCOVER"),
            json!("DHCPOFFER"),
            json!("DHCPREQUEST"),
            json!("DHCPACK"),
            Value::Null
        ]
    );

    let discover = app(&p[0]).unwrap();
    assert_eq!(discover["transaction_id"], 0x3903_F326u32);
    assert_eq!(discover["broadcast"], true);
    assert_eq!(discover["client_mac"], "02:00:00:00:00:01");
    assert_eq!(discover["hostname"], "lab-host-01");
    assert_eq!(discover["option_codes"], json!([53, 61, 55, 12]));

    let request = app(&p[2]).unwrap();
    assert_eq!(request["requested_ip"], "192.0.2.10");
    assert_eq!(request["server_identifier"], "192.0.2.1");
    let ack = app(&p[3]).unwrap();
    assert_eq!(ack["your_ip"], "192.0.2.10");
    assert_eq!(ack["lease_time_seconds"], 86400);
    assert_eq!(warning_codes(&p[4]), ["unrecognized_application_data"]);
}

#[test]
fn http_fixture_redacts_credentials() {
    let p = packets("app-http.pcap");
    let request = app(&p[0]).unwrap();
    assert_eq!(request["method"], "GET");
    assert_eq!(request["path"], "/index.html");
    assert_eq!(request["query_redacted"], true);
    assert_eq!(request["host"], "www.example.com");
    assert_eq!(
        request["redacted_headers"],
        json!(["authorization", "cookie"])
    );
    assert!(warning_codes(&p[0]).contains(&"sensitive_data_redacted".to_owned()));

    let response = app(&p[1]).unwrap();
    assert_eq!(response["status_code"], 200);
    assert_eq!(response["reason"], "OK");
    assert_eq!(response["content_type"], "text/html");
    assert_eq!(response["content_length"], 37);
    assert_eq!(response["connection"], "keep-alive");
    assert_eq!(response["redacted_headers"], json!(["set-cookie"]));

    let post = app(&p[2]).unwrap();
    assert_eq!(post["path"], "/login");
    assert_eq!(post["userinfo_redacted"], true);
    assert_eq!(post["version"], "HTTP/1.0");

    assert_eq!(app(&p[3]).unwrap()["host"], "www.example.com:8080");
    assert!(
        app(&p[4]).is_none(),
        "non-HTTP bytes on port 80 stay unknown"
    );

    let embedded = app(&p[5]).unwrap();
    assert_eq!(embedded["path"], "/fetch/{redacted}");
    assert_eq!(embedded["path_segments_redacted"], 1);
}

#[test]
fn tls_fixture_is_handshake_metadata_only() {
    let p = packets("app-tls.pcap");
    let hello = app(&p[0]).unwrap();
    assert_eq!(
        hello["visibility"],
        "visible handshake metadata only; nothing is decrypted"
    );
    assert_eq!(hello["handshake_type_name"], "client_hello");
    assert_eq!(hello["server_name"], "www.example.com");
    assert_eq!(hello["alpn"], json!(["h2", "http/1.1"]));
    assert_eq!(hello["supported_versions"], json!([0x2A2A, 0x0304, 0x0303]));
    assert_eq!(hello["supported_groups"], json!([0x001D, 0x0017]));
    assert_eq!(hello["cipher_suite_count"], 6);
    assert_eq!(hello["complete"], true);
    let ext_names: Vec<&str> = hello["extensions"]
        .as_array()
        .unwrap()
        .iter()
        .map(|e| e["name"].as_str().unwrap())
        .collect();
    assert!(ext_names.contains(&"key_share"));

    let server = app(&p[1]).unwrap();
    assert_eq!(server["negotiated_version_name"], "TLS 1.3");
    assert_eq!(server["cipher_suites"], json!([0x1301]));

    assert!(app(&p[2]).is_none(), "certificate messages are not parsed");
    assert!(app(&p[3]).is_none(), "encrypted records are not parsed");
    assert_eq!(
        app(&p[4]).unwrap()["server_name"],
        "api.example.org",
        "TLS on port 8443"
    );
}

#[test]
fn no_secret_or_payload_reaches_any_output() {
    for name in [
        "app-dns.pcap",
        "app-dhcp.pcap",
        "app-http.pcap",
        "app-tls.pcap",
    ] {
        for extra in [
            &["--decode"][..],
            &["--decode", "--verbose"],
            &["--decode", "--json"],
            &["--json"],
        ] {
            let out = run(name, extra);
            // Hosts and server names are lowercased, so compare without case.
            let text = String::from_utf8_lossy(&out.stdout).to_ascii_lowercase();
            for fragment in [
                SECRET_MARKER,
                PAYLOAD_MARKER,
                "alice",
                "tls-random",
                "session-id",
                "keyshare",
                "-txt",
            ] {
                let fragment = fragment.to_ascii_lowercase();
                assert!(
                    !text.contains(&fragment),
                    "{name} {extra:?} leaked {fragment}"
                );
            }
        }
    }
}

#[test]
fn human_output_labels_tls_and_redactions() {
    let text = String::from_utf8(run("app-tls.pcap", &["--decode"]).stdout).unwrap();
    assert!(text.contains(
        "TLS ClientHello SNI=www.example.com ALPN=h2,http/1.1 (handshake metadata only)"
    ));
    let text = String::from_utf8(run("app-tls.pcap", &["--decode", "--verbose"]).stdout).unwrap();
    assert!(
        text.contains("TLS: visible handshake metadata only; nothing is decrypted: client_hello")
    );
    let text = String::from_utf8(run("app-http.pcap", &["--decode"]).stdout).unwrap();
    assert!(text.contains("GET /index.html HTTP/1.1 host=www.example.com [redacted]"));
    let text = String::from_utf8(run("app-dns.pcap", &["--decode"]).stdout).unwrap();
    assert!(
        text.contains(
            "response 0x1a2b NOERROR A www.example.com -> web.example.com, 198.51.100.80"
        )
    );
}
