//! Runs `flowsentinel inspect --decode` end to end against the decoder
//! fixtures generated by scripts/generate_pcap_fixtures.py.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::path::PathBuf;
use std::process::{Command, Output};

use serde_json::Value;

/// Must match PAYLOAD_MARKER in scripts/generate_pcap_fixtures.py.
const PAYLOAD_MARKER: &str = "FLOWSENTINEL-SYNTHETIC-PAYLOAD-MARKER";

fn run(name: &str, extra: &[&str]) -> Output {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/pcap")
        .join(name);
    Command::new(env!("CARGO_BIN_EXE_flowsentinel"))
        .arg("inspect")
        .arg("--pcap")
        .arg(path)
        .args(extra)
        .output()
        .expect("failed to run flowsentinel binary")
}

fn json(name: &str) -> Value {
    let out = run(name, &["--decode", "--json"]);
    assert_eq!(out.status.code(), Some(0), "{name}");
    serde_json::from_slice(&out.stdout).expect("one JSON object")
}

fn layer<'a>(packet: &'a Value, name: &str) -> &'a Value {
    packet["decoded"]["layers"]
        .as_array()
        .unwrap()
        .iter()
        .find(|l| l["layer"] == name)
        .unwrap_or_else(|| panic!("no {name} layer in {packet}"))
}

fn statuses(report: &Value) -> Vec<String> {
    report["packets"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| p["decoded"]["status"].as_str().unwrap().to_owned())
        .collect()
}

#[test]
fn ipv4_fixture_decodes_every_protocol() {
    let report = json("decode-ipv4.pcap");
    assert!(statuses(&report).iter().all(|s| s == "complete"));
    let packets = report["packets"].as_array().unwrap();
    assert_eq!(packets.len(), 14);

    let arp = layer(&packets[0], "arp");
    assert_eq!(arp["operation_name"], "request");
    assert_eq!(arp["target_ip"], "192.0.2.1");
    assert_eq!(
        layer(&packets[0], "ethernet")["destination"],
        "ff:ff:ff:ff:ff:ff"
    );

    let syn = layer(&packets[3], "tcp");
    assert_eq!(syn["flags"]["names"], serde_json::json!(["SYN"]));
    assert_eq!(syn["header_length"], 28);
    let syn_ack = layer(&packets[4], "tcp");
    assert_eq!(syn_ack["flags"]["names"], serde_json::json!(["SYN", "ACK"]));
    assert_eq!(
        layer(&packets[6], "tcp")["payload_length"],
        PAYLOAD_MARKER.len()
    );

    assert_eq!(layer(&packets[8], "icmp")["type_name"], "echo request");
    assert_eq!(
        layer(&packets[10], "ethernet")["vlan_tags"][0]["vlan_id"],
        10
    );
    assert_eq!(
        layer(&packets[11], "ethernet")["vlan_tags"][0]["tpid"],
        0x88A8
    );

    // The non-initial fragment has no transport layer.
    assert_eq!(
        packets[13]["decoded"]["layers"].as_array().unwrap().len(),
        2
    );
    assert_eq!(layer(&packets[13], "ipv4")["fragment_offset"], 24);

    let summary = &report["decode_summary"];
    assert_eq!(summary["packets_decoded"], 14);
    assert_eq!(summary["protocol_counts"]["tcp"], 5);
    assert_eq!(summary["protocol_counts"]["arp"], 2);
}

#[test]
fn ipv6_fixture_traverses_extension_headers() {
    let report = json("decode-ipv6.pcap");
    assert_eq!(
        statuses(&report),
        [
            "complete",
            "complete",
            "complete",
            "complete",
            "complete",
            "complete",
            "complete",
            "unsupported",
            "complete"
        ]
    );
    let packets = report["packets"].as_array().unwrap();
    let ip = layer(&packets[4], "ipv6");
    assert_eq!(ip["extension_headers"].as_array().unwrap().len(), 2);
    assert_eq!(ip["upper_layer_name"], "UDP");
    assert_eq!(
        layer(&packets[3], "icmpv6")["type_name"],
        "neighbor solicitation"
    );
    assert_eq!(
        layer(&packets[5], "ipv6")["fragment"]["more_fragments"],
        true
    );
    assert_eq!(
        packets[7]["decoded"]["warnings"][0]["code"],
        "encrypted_payload"
    );
}

#[test]
fn malformed_packets_do_not_stop_later_packets() {
    let report = json("decode-malformed.pcap");
    assert_eq!(
        statuses(&report),
        [
            "truncated",
            "malformed",
            "malformed",
            "malformed",
            "malformed",
            "malformed",
            "malformed",
            "truncated",
            "malformed",
            "malformed",
            "truncated",
            "malformed",
            "complete"
        ]
    );
    let warning = |i: usize| report["packets"][i]["decoded"]["warnings"][0]["code"].clone();
    assert_eq!(warning(9), "length_mismatch");
    assert_eq!(warning(10), "truncated_header");
    assert_eq!(warning(11), "length_mismatch");
    assert_eq!(report["completion_state"], "complete");
}

#[test]
fn unsupported_link_types_are_reported_per_packet() {
    let report = json("decode-raw-linktype.pcap");
    assert_eq!(statuses(&report), ["unsupported", "unsupported"]);
    assert_eq!(
        report["decode_summary"]["warnings"][0]["code"],
        "unsupported_link_type"
    );
    assert_eq!(report["decode_summary"]["warnings"][0]["count"], 2);
}

#[test]
fn unsupported_protocols_keep_outer_layers() {
    let report = json("decode-unsupported.pcap");
    assert_eq!(
        statuses(&report),
        [
            "unsupported",
            "unsupported",
            "unsupported",
            "unsupported",
            "complete"
        ]
    );
    let gre = &report["packets"][2];
    assert_eq!(layer(gre, "ipv4")["protocol_name"], "GRE");
}

#[test]
fn human_output_has_table_and_verbose_tree() {
    let out = run("decode-ipv4.pcap", &["--decode"]);
    let text = String::from_utf8(out.stdout).unwrap();
    assert!(text.contains("Decode summary"));
    assert!(text.contains("who-has 192.0.2.1 tell 192.0.2.10"));
    assert!(text.contains("40001 -> 9 [SYN] seq=1000 win=64240 len=0"));
    assert!(!text.contains("Ethernet II:"));

    let out = run("decode-ipv4.pcap", &["--decode", "--verbose"]);
    let text = String::from_utf8(out.stdout).unwrap();
    assert!(text.contains("Ethernet II: 02:00:00:00:00:01 -> ff:ff:ff:ff:ff:ff"));
    assert!(text.contains("TCP: 40001 -> 9, flags SYN, seq 1000"));
    assert!(text.contains("Frame: 79 bytes captured"));
}

#[test]
fn decode_output_never_contains_payload() {
    for name in [
        "decode-ipv4.pcap",
        "decode-ipv6.pcap",
        "decode-unsupported.pcap",
        "decode-malformed.pcap",
        "decode-raw-linktype.pcap",
    ] {
        for extra in [
            &["--decode"][..],
            &["--decode", "--verbose"],
            &["--decode", "--json"],
        ] {
            let out = run(name, extra);
            assert_eq!(out.status.code(), Some(0), "{name} {extra:?}");
            let stdout = String::from_utf8_lossy(&out.stdout);
            assert!(!stdout.contains(PAYLOAD_MARKER), "{name} {extra:?}");
            assert!(!stdout.contains("SYNTHETIC"), "{name} {extra:?}");
        }
    }
}

#[test]
fn json_without_decode_is_unchanged() {
    let out = run("decode-ipv4.pcap", &["--json"]);
    let value: Value = serde_json::from_slice(&out.stdout).unwrap();
    assert!(value.get("decode_summary").is_none());
    assert!(value["packets"][0].get("decoded").is_none());
}

#[test]
fn verbose_without_decode_is_a_usage_error() {
    let out = run("decode-ipv4.pcap", &["--verbose"]);
    assert_eq!(out.status.code(), Some(2));
}

#[test]
fn decode_respects_packet_limit() {
    let out = run(
        "decode-ipv4.pcap",
        &["--decode", "--json", "--max-packets", "3"],
    );
    let value: Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(value["packets"].as_array().unwrap().len(), 3);
    assert_eq!(value["decode_summary"]["packets_decoded"], 3);
    assert_eq!(value["completion_state"], "packet_limit_reached");
}
